# Week 1 - Assignment

This notebook contains scenario-based Python along with their solutions. It covers topics such as Python basics, data structures, NumPy, pandas, and data types. 


###  1. Scenario: You have a list of integers, and you need to find the maximum value in the list. 

a. Question: How would you find the maximum value from the following list? 

In [1]:
# finding the maximum value from the following list

num = numbers = [4, 7, 1, 9, 3, 6]

print(max(num))

9


### 2. Scenario: You need to concatenate a list of strings into a single string, with each string separated by a comma. 

a. Question: How would you combine the following list of strings into a single string? 

In [2]:
# combining the list of strings into a single string 
name = ['Kalpana', 'Rajesh', 'Asmita', 'Manjeel', 'Josiah', 'Destiny']
results = ", ".join(name)
print(results)

Kalpana, Rajesh, Asmita, Manjeel, Josiah, Destiny


### 3. Scenario: You have a dictionary where the keys are names and the values are ages. You need to retrieve the age of a specific person. 

a. Question: How would you get the age of "Dev" from the following dictionary? 

In [3]:
# finding the age of Dev using index method 
age = {"Bob":25, "Charle":23, "Eve":20, "Dev":28}
print(age["Dev"]) 

28


### 4. Scenario: You need to remove duplicate elements from a list while preserving the original order of elements.

a. Question: How would you remove duplicates from the following list? 

In [4]:
list_dup = [1,2, 3, 5, 6,7 ,8,5,6,7,8,9,9]
set_dup = set()
uniq_list = [x for x in list_dup if not (x in set_dup or set_dup.add(x))]
uniq_list


[1, 2, 3, 5, 6, 7, 8, 9]

### 5. Scenario: You have a NumPy array and need to compute the sum of all its elements. 

a. Question: How would you find the sum of elements in the following NumPy array? 

In [5]:
import numpy as np 

num_array = np.array([1,2,3,4,5,6])
print(sum(num_array))

21


### 6. Scenario: You have a 2D NumPy array and need to get the maximum value from each column.

a. Question: How would you find the maximum values for each column in the following array? 

In [6]:
array = np.array([[1,2,3],
                [4,5,6], 
                [9,7,10]])
max_value = np.max(array, axis =0)
print(max_value)

[ 9  7 10]


### 7. Scenario: You have a DataFrame and need to sort it by a specific column.

a. Question: How would you sort the DataFrame by the "Age" column? 

In [7]:
import pandas as pd 

data = {'Name': ['Kalpana', 'Rajesh', 'Josiah', 'Destiny'], 
       'Age': [28,27,15,10]}
df = pd.DataFrame(data)

In [8]:
sort_df = df.sort_values(by='Age')
print(sort_df)

      Name  Age
3  Destiny   10
2   Josiah   15
1   Rajesh   27
0  Kalpana   28


### 8. Scenario: You need to calculate the total sum of a column in a DataFrame. 

a. Question: How would you find the sum of the "Sales" column? 

In [9]:
data_1 = { 'product': ['Apple', 'Banana','Orange', 'Citrus'],
         'Sales': [10, 15, 40, 100]}
df_sales = pd.DataFrame(data_1)
sum_sales = df_sales['Sales'].sum()
print(sum_sales)

165


### 9. Scenario: You need to check if a variable is of type int.

a. Question: How would you verify if a variable x is an integer? 

In [10]:
numb = 5.0 
print(numb.is_integer())

True


### 10. Scenario: You have a list of mixed types and need to create separate lists for integers, floats, and strings.

a. Question: How would you categorize the following mixed list into different types? 

In [11]:
# created a mixed types of list 
mixed_list = [1, 2.5, 'apple', 3, 4.0, 'banana', 5, 6.7, 'cherry']

# Initialize separate lists
integers = []
floats = []
strings = []

In [12]:
# creating a list using for loop and if else statement 

for i in mixed_list:
    if isinstance(i, int): 
        integers.append(i)
    elif isinstance(i, float):
        floats.append(i)
    elif isinstance(i, str): 
        strings.append(i)
        

In [13]:
print(integers)
print(floats)
print(strings)

[1, 3, 5]
[2.5, 4.0, 6.7]
['apple', 'banana', 'cherry']


### 11. Scenario: You are given a string of comma-separated numbers. You need to convert this string into a list of integers. 

a. Question: How would you achieve this conversion? 

In [14]:
# created a variable name num_str with comma-separated numbers 
num_str = '1,2,3,4,5,6'
# split the numbers 
num = num_str.split(',')
num

['1', '2', '3', '4', '5', '6']

In [15]:
# Converted 
int_list = [int(x)for x in num]
print(int_list)

[1, 2, 3, 4, 5, 6]


### 12. Scenario: You need to reverse the words in a sentence while keeping the order of the words intact.

a. Question: How would you reverse each word in the following sentence? 

In [16]:
# step 1: split the sentence into words
sen = 'Hello I am Kalpana'
words = sen.split()
words

['Hello', 'I', 'am', 'Kalpana']

In [17]:
# Step 2: Reverse each word
rev_words = [word[::-1] for word in words]

# Step 3: Join the reversed words back into a sentence
rev_sen = ' '.join(rev_words)

print(rev_sen)


olleH I ma anaplaK


### 13. Scenario: You need to combine two lists into a dictionary where the elements of the first list are keys and the elements of the second list are values. 

a. Question: How would you combine the following lists into a dictionary? 

In [18]:
first_name = ['Kalpana', 'Rajesh', 'Asmita', 'Josiah']
last_name = ['Biswa', 'Chaulagain', 'Shrestha', 'Baral']
first_last_name = dict(zip(first_name, last_name))
print(first_last_name)

{'Kalpana': 'Biswa', 'Rajesh': 'Chaulagain', 'Asmita': 'Shrestha', 'Josiah': 'Baral'}


### 14. Scenario: You are given a list of tuples where each tuple contains a name and an age. You need to sort this list by age. 

a. Question: How would you sort the following list of tuples by age? 

In [19]:
people = [('Jade', 30), ('Ray', 25), ('Chris', 35), ('Maya', 20)]
sorted_people = sorted(people, key=lambda x: x[1])
print(sorted_people)


[('Maya', 20), ('Ray', 25), ('Jade', 30), ('Chris', 35)]


### 15. Scenario: You have a 2D NumPy array and need to calculate the mean value of each row.

a. Question: How would you compute the mean value for each row in the following array? 

In [20]:
array = np.array([[1,2,3],
                [4,5,6], 
                [9,7,10]])
mean_value = np.mean(array, axis =1)
print(mean_value)

[2.         5.         8.66666667]


### 16. Scenario: You need to create a NumPy array of size 10 filled with zeros, and then set the fifth element to 5. 

a. Question: How would you create and modify the array as described? 

In [21]:
array_np = np.zeros(10)
array_np[4]=5
print(array_np)

[0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]


### 17. Scenario: You have a DataFrame and need to find the median of a numeric column. 

a. Question: How would you find the median of the "Scores" column in the following DataFrame? 

In [22]:
import pandas as pd
data_score = {'Name': ['Kaleb', 'Raj', 'Dev', 'Ram'], 'Scores': [80, 90, 87, 95]}
df_score  = pd.DataFrame(data_score)

In [23]:
median_score = df_score['Scores'].median()
median_score

88.5

### 18. Scenario: You need to filter rows where the value in the "Sales" column is above 100 and then sort these rows by "Date" in descending order.

a. Question: How would you filter and sort the DataFrame based on the given criteria? 

In [24]:
import pandas as pd

sales_data = {'Date': ['2024-08-01', '2024-08-02', '2024-08-03', '2024-08-04'],
              'Sales': [150, 85, 200, 120],
              'Product': ['A', 'B', 'C', 'D']}

df = pd.DataFrame(sales_data)
filtered_df = df[df['Sales'] > 100]
sorted_df = filtered_df.sort_values(by='Date', ascending=False)
print(sorted_df)


         Date  Sales Product
3  2024-08-04    120       D
2  2024-08-03    200       C
0  2024-08-01    150       A


### 19. Scenario: You have a string containing a number and need to convert it to an integer. Additionally, handle the case where the string might not represent a valid integer. 

a. Question: How would you safely convert the string "42" to an integer and handle invalid cases? 

In [25]:
numbers = "42"
num = int(numbers)
print(num)

42


### 20. Scenario: You have a list containing different data types, and you want to separate out all the strings.

a. Question: How would you extract all string elements from the following list? 

In [26]:
mixed_list = [2,4.5, 'Kalpana', 'Ramsy','2.6', True, False, 'Apple', 34 ]
str_element = [i for i in mixed_list if isinstance(i, str)]
str_element

['Kalpana', 'Ramsy', '2.6', 'Apple']